name: Merge and Test

on:
  push:
    branches:
      - sub

jobs:
  merge_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge sub branch
        run: |
          git checkout main
          git merge sub
          git push origin main

      - name: Run Tests
        run: |
          # Add commands to run your tests here
          echo "Tests are running..."

