name: Merge and Test

on:
  push:
    branches:
      - Abranch
      - Bbranch

jobs:
  merge_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Abranch
        run: |
          git checkout Cmain
          git merge Abranch
          git push origin Cmain

      - name: Merge Bbranch
        run: |
          git checkout Cmain
          git merge Bbranch
          git push origin Cmain

      - name: Run Tests
        run: |
          # Add commands to run your tests here
          echo "Tests are running..."

