name: Merge and Test

on:
  push:
    branches:
      - main

jobs:
  merge_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge sub branch
        run: |
          git checkout sub
          git merge main
          git push origin sub

      - name: Run Tests
        run: |
          # Add commands to run your tests here
          echo "Tests are running..."

